# tap brew
tap 'homebrew/bundle'
tap 'homebrew/core'
tap 'homebrew/versions'
tap 'homebrew/dupes'
tap 'homebrew/services'

tap 'caskroom/cask'
tap 'caskroom/fonts'
tap 'caskroom/versions'
tap 'neovim/neovim'
tap 'homebrew/php'

cask_args appdir: '/Applications'

# brew install
brew 'autoconf'
brew 'automake'
brew 'coreutils'
brew 'findutils'
brew 'moreutils'
brew 'wget', args: ['with-iri']
brew 'gnu-sed', args: ['with-default-names']
brew 'cmake'
brew 'gdbm'
brew 'gettext'
brew 'pcre'
brew 'git'
brew 'git-lfs'
brew 'libtool'
brew 'python'
brew 'libxml2', args: ['with-python']
brew 'lzlib'
brew 'pkg-config'
brew 'openssl'
brew 'node'
brew 'readline'
brew 'pyenv'
brew 'zsh'
brew 'homebrew/versions/libxml278'
brew 'neovim/neovim/neovim'
brew 'tmux'
brew 'mas'
brew 'tig'
brew 'nginx'
brew 'php70', args: ['without-apache', 'with-fpm', 'with-mysql']
brew 'mackup'

# cask applications
cask 'gpgtools'
cask 'intellij-idea'
cask 'iterm2'
cask 'google-chrome'
cask 'java' unless system '/usr/libexec/java_home --failfast'
cask 'sublime-text-dev'
cask 'telegram'
cask 'adobe-photoshop-cc'
cask 'adobe-photoshop-lightroom'
cask 'tower'
cask 'sqlitebrowser'
cask 'macdown'
cask 'busycal'
cask 'utorrent'
cask 'istat-menus'
cask 'android-studio'
cask 'transmission'

# cask fonts
cask 'font-d2coding'
cask 'font-hack.rb'
cask 'font-meslo-lg-for-powerline'
cask 'font-meslo-lg'
cask 'font-nanumgothic'
cask 'font-nanummyeongjo'

